- DependencyInjection/DoctrineExtension.php
> Fix minor typo

- Resources/doc/configuration.rst
This PR was originally sent to symfony/symfony-docs#4719. Since the discussion there and in https://github.com/doctrine/DoctrineBundle/pull/360#issuecomment-68607391 results in the decision to maintain the config reference documentation here in the Bundle repo, the configuration reference should be updated here. I opened this PR as asked by @stof in https://github.com/symfony/symfony-docs/pull/4719#issuecomment-70341286
> Update configuration reference

- Controller/ProfilerController.php
> PHP syntax error

- DependencyInjection/DoctrineExtension.php
fixes #410 serverVersion isn't found when MasterSlaveConnection is used
> Fix the serverVersion configuration for master slave connections

- DependencyInjection/Configuration.php
- DependencyInjection/DoctrineExtension.php
- Resources/config/orm.xml
- Resources/config/schema/doctrine-1.0.xsd
- Resources/doc/configuration.rst
- Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
- Tests/DependencyInjection/DoctrineExtensionTest.php
- Tests/DependencyInjection/Fixtures/config/xml/orm_quotestrategy.xml
- Tests/DependencyInjection/Fixtures/config/yml/orm_quotestrategy.yml
> integrate quote_strategy into config

- Command/DropDatabaseDoctrineCommand.php
> formatted help and highlighted --force parameter

- composer.json
See guilhermeblanco response on the PR430
Still to fix the hhvm build
> Removing a temporary solution to doctrine common not being tagged

- Command/GenerateEntitiesDoctrineCommand.php
- Command/ImportMappingDoctrineCommand.php
- Command/Proxy/RunDqlDoctrineCommand.php
- Command/Proxy/RunSqlDoctrineCommand.php
> fixed command helps

- Tests/BundleTest.php
RegisterEventListenersAndSubcribersPass => RegisterEventListenersAndSubscribersPass
> Fix small typo

- Resources/views/Collector/db.html.twig
> Fixed incorrect link text after clicking on it

- DependencyInjection/Configuration.php
- Resources/config/schema/doctrine-1.0.xsd
- Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
- Tests/DependencyInjection/Fixtures/config/xml/dbal_oracle_connectstring.xml
- Tests/DependencyInjection/Fixtures/config/xml/dbal_oracle_instancename.xml
- Tests/DependencyInjection/Fixtures/config/yml/dbal_oracle_connectstring.yml
- Tests/DependencyInjection/Fixtures/config/yml/dbal_oracle_instancename.yml
> Adding the connectstring and instancename param of oracle

- Resources/views/Collector/db.html.twig
According to the [status](https://github.com/bocharsky-bw/DoctrineBundle/blob/patch-1/Resources/views/Collector/db.html.twig#L22) variable.
> Highlight query count box according to the db toolbar icon status

- Command/Proxy/ImportDoctrineCommand.php
There's already a command for that in Doctrine/DBAL.
> Add doctrine:database:import command to load SQL files

- Resources/doc/configuration.rst
> Add documentation on the oracle session environment

- composer.json
and make a new release please.
> add twig/twig version 2.0

- Command/Proxy/CreateSchemaDoctrineCommand.php
- Command/Proxy/DropSchemaDoctrineCommand.php
@stof, i only see those two missing but i may miss something.
> Add missing returns to cerate & drop schema commands

- Resources/doc/configuration.rst
see http://symfony.com/doc/build_errors
> fix section title markup

- DependencyInjection/DoctrineExtension.php
- composer.json
Fixing my previous PR sorry, I should not have added symfony/form as a dev-dep because it hides the issue.
> Fix check for DoctrineType::reset() existence

- Command/CreateDatabaseDoctrineCommand.php
- DataCollector/DoctrineDataCollector.php
- DependencyInjection/DoctrineExtension.php
- DoctrineBundle.php
- Resources/config/dbal.xml
- Tests/Command/CreateDatabaseDoctrineTest.php
- Tests/DependencyInjection/DoctrineExtensionTest.php
- composer.json
I've just created a 1.6 branch where I can backport critical changes. That would partially solve the issue mentioned in #704.
> Backport some critical issues/changes to the 1.6 branch

- .travis.yml
Migrating Travis builds to Build Stages & sync with other Doctrine projects.
Same amount of green/red stages as before, but it'd be indeed better to fix CI in master beforehand.
> Build Stages

- Controller/ProfilerController.php
Accidentally introduced in #772.
> Revert Exception -> Throwable due to PHP 5.x support

- .travis.yml
- Command/DropDatabaseDoctrineCommand.php
- Command/GenerateEntitiesDoctrineCommand.php
- Command/ImportMappingDoctrineCommand.php
- Command/Proxy/ConvertMappingDoctrineCommand.php
- Command/Proxy/DelegateCommand.php
- Command/Proxy/DoctrineCommandHelper.php
- ConnectionFactory.php
- Controller/ProfilerController.php
- DataCollector/DoctrineDataCollector.php
- DependencyInjection/Configuration.php
- DependencyInjection/DoctrineExtension.php
- DoctrineBundle.php
- ManagerConfigurator.php
- Mapping/ContainerAwareEntityListenerResolver.php
- Mapping/DisconnectedMetadataFactory.php
- Tests/ConnectionFactoryTest.php
- Tests/ContainerTest.php
- Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
- Tests/DependencyInjection/DoctrineExtensionTest.php
- Tests/DependencyInjection/XMLSchemaTest.php
- Tests/Mapping/ContainerAwareEntityListenerResolverTest.php
- Tests/Mapping/DisconnectedMetadataFactoryTest.php
- Tests/ServiceRepositoryTest.php
- Tests/TestCase.php
- Twig/DoctrineExtension.php
- phpcs.xml.dist
I just couldn't add `composer.lock` :(
> Apply Doctrine CS v4

- Command/ImportMappingDoctrineCommand.php
This is probably a copy/paste/adapt mistake.
> Describe the actual command

- DependencyInjection/DoctrineExtension.php
- composer.json
> Inject the EntityManager instead of the factory in DoctrineExtractor

- .travis.yml
Fixing the build on Symfony 4.1 and adding a build for 4.2.
> Make travis green

- Registry.php
> Fix php doc block

- .travis.yml
This cleans up the build pipeline and removes obsolete configuration.
> Update build pipeline

- Command/Proxy/CollectionRegionDoctrineCommand.php
- Command/Proxy/EntityRegionCacheDoctrineCommand.php
- Command/Proxy/QueryRegionCacheDoctrineCommand.php
Fixes an issue reported in #976, previously introduced in #892.
> Fix usage of wrong option in previously delegated commands

- Tests/Command/ImportMappingDoctrineCommandTest.php
- Tests/DependencyInjection/Fixtures/config/xml/dbal_service_pool_sharding_connection.xml
- Tests/DependencyInjection/Fixtures/config/xml/orm_repository_factory.xml
- Tests/DependencyInjection/Fixtures/config/xml/orm_second_level_cache.xml
- Tests/DependencyInjection/Fixtures/config/yml/dbal_service_pool_sharding_connection.yml
- Tests/DependencyInjection/Fixtures/config/yml/orm_repository_factory.yml
See failures in https://travis-ci.org/doctrine/DoctrineBundle/builds/561641950.
> Fix build failures in combination with Symfony 4.4 and newer

- Tests/Command/ImportMappingDoctrineCommandTest.php
This fixes an issue introduced in #996 that causes erroneous files to be present in the project directory.
> Fix workaround for missing getProjectDir method

- DependencyInjection/Configuration.php
- DependencyInjection/DoctrineExtension.php
- Registry.php
- Tests/Dbal/Logging/BacktraceLoggerTest.php
- Tests/ProfilerTest.php
- composer.json
* Add return type hints for compatibility with Symfony 5
* Stop mocking class that's final in Symfony 5
> Fix deprecations from Symfony 4.4

- Controller/ProfilerController.php
> Use EXPLAIN QUERY PLAN on SQLite

- DependencyInjection/Compiler/EntityListenerPass.php
- Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
- Tests/DependencyInjection/Fixtures/config/xml/orm_attach_entity_listener_tag.xml
- Tests/DependencyInjection/Fixtures/config/yml/orm_attach_entity_listener_tag.yml
Fixes https://github.com/doctrine/DoctrineBundle/pull/989#discussion_r309244615
> [EntityListenerPass] Handle ChildDefinition

- Resources/config/dbal.xml
- Resources/config/orm.xml
> Always register ImportDoctrineCommand

- Resources/config/dbal.xml
- Resources/config/orm.xml
- Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomServiceRepoRepository.php
- UPGRADE-1.12.md
Trigger a deprecated message on services alias that will be removed in doctrine 2
https://github.com/doctrine/DoctrineBundle/pull/1048#discussion_r346353245
> Deprecated alias for common interfaces

- DependencyInjection/DoctrineExtension.php
- Resources/config/dbal.xml
- Resources/config/orm.xml
> Deprecated alias on DI Extension

- DependencyInjection/Compiler/WellKnownSchemaFilterPass.php
- Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
- Tests/DependencyInjection/Fixtures/config/xml/well_known_schema_filter_default_tables_cache.xml
- Tests/DependencyInjection/Fixtures/config/xml/well_known_schema_filter_default_tables_lock.xml
- Tests/DependencyInjection/Fixtures/config/xml/well_known_schema_filter_default_tables_messenger.xml
- Tests/DependencyInjection/Fixtures/config/xml/well_known_schema_filter_default_tables_session.xml
- Tests/DependencyInjection/Fixtures/config/xml/well_known_schema_filter_overridden_tables_cache.xml
- Tests/DependencyInjection/Fixtures/config/xml/well_known_schema_filter_overridden_tables_lock.xml
- Tests/DependencyInjection/Fixtures/config/xml/well_known_schema_filter_overridden_tables_messenger.xml
- Tests/DependencyInjection/Fixtures/config/xml/well_known_schema_filter_overridden_tables_session.xml
- Tests/DependencyInjection/Fixtures/config/yml/well_known_schema_filter_default_tables_cache.yml
- Tests/DependencyInjection/Fixtures/config/yml/well_known_schema_filter_default_tables_lock.yml
- Tests/DependencyInjection/Fixtures/config/yml/well_known_schema_filter_default_tables_messenger.yml
- Tests/DependencyInjection/Fixtures/config/yml/well_known_schema_filter_default_tables_session.yml
- Tests/DependencyInjection/Fixtures/config/yml/well_known_schema_filter_overridden_tables_cache.yml
- Tests/DependencyInjection/Fixtures/config/yml/well_known_schema_filter_overridden_tables_lock.yml
- Tests/DependencyInjection/Fixtures/config/yml/well_known_schema_filter_overridden_tables_messenger.yml
- Tests/DependencyInjection/Fixtures/config/yml/well_known_schema_filter_overridden_tables_session.yml
> fix well known schema filter blacklist tables

- Registry.php
- Tests/RegistryTest.php
- composer.json
Release [2.0.6](https://github.com/doctrine/DoctrineBundle/milestone/34)
2.0.6
=====
- Total issues resolved: **0**
- Total pull requests resolved: **0**
- Total contributors: **0**
> Merge release 2.0.6 into master

- DependencyInjection/DoctrineExtension.php
We forgot to remove this in https://github.com/doctrine/DoctrineBundle/pull/1029
see also https://github.com/doctrine/DoctrineBundle/pull/1124
> Remove last remaining doctrine cache related code

- Tests/CacheSchemaSubscriberTest.php
- Tests/DataCollector/DoctrineDataCollectorTest.php
> Skip ORM tests on php 8

- DependencyInjection/Configuration.php
- DependencyInjection/DoctrineExtension.php
- Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
> Fix use default lifetime and lock lifetime

- .github/workflows/coding-standards.yml
- .travis.yml
This is part of an effort to standardize jobs across repositories.
> Migrate cs job to Github Actions

- DoctrineBundle.php
Such is our coding standard.
This should fix the build for branch master
> Use early return

- .travis.yml
- Tests/CacheSchemaSubscriberTest.php
- Tests/ServiceRepositoryTest.php
This should fix the error from here:
https://travis-ci.org/github/doctrine/DoctrineBundle/jobs/737975932
Related pull request to this pipeline: 
https://github.com/doctrine/DoctrineBundle/pull/1234
If this work, this should also merged to branch 2.1.x
> Make tests compatible with symfony/http-kernel 5.2

- Command/Proxy/DoctrineCommandHelper.php
- DataCollector/DoctrineDataCollector.php
- DoctrineBundle.php
- Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
> Fix incorrect assertions
