doctrine/DoctrineBundle

Tests/DataCollector/DoctrineDataCollectorTest.php
phpunit.xml.dist

This is the first step in making the test suite go green again. It makes the `Doctrine\Bundle\DoctrineBundle\Tests\DataCollector\DoctrineDataCollectorTest` compatible with ORM < 2.5.0-DEV again.
The test suite is still failing because of recent Symfony deprecations. Also composer is still installing ORM `2.4.x-dev` while it should install `dev-master` IMO.
Both issues should be dealt with separately though.

Make data collector test compatible with different ORM versions

---

DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/DoctrineExtensionTest.php

Replacement for doctrine/DoctrineBundle#371
Regarding the error in [this post](https://github.com/doctrine/DoctrineCacheBundle/issues/38#issuecomment-69631811), it seems that the extension currently has 2 problems:
1. A `printf` call that should be `sprintf`
2. An alias with the wrong name
It seems to me that either the alias name should be changed from `doctrine.orm.<cache_provider>` to `doctrine.orm.<entity_manager>_<cache_provider>`, or that this alias should be added, besides the current alias. I prefer the first one as it creates 1 working alias, but I'm not sure if it will break things when `doctrine.orm.<cache_provider>` is no longer available.
This PR uses the first solution, if it should be solved differently let me know.

Fixed cache provider alias in extension

---

Command/DropDatabaseDoctrineCommand.php

A recent fix in DBAL https://github.com/doctrine/dbal/commit/4a603c7a711f9399dbb03b5b88b8ecce8c41df84 makes the drop database command fail on PostgreSQL. PostgreSQL does not allow dropping a database currently opened by a connection so instead a "temporary" connection without database name specified should be used to drop the database (as already done in create database command).
Successfully tested this with MySQL, SQLite, PostgreSQL, SQL Anywhere, SQL Server (DB2 and Oracle do not support dropping and creating databases anyways).
See: http://www.doctrine-project.org/jira/browse/DBAL-1114

[DBAL-1114] Drop database without having it opened

---

Resources/doc/configuration.rst

This all started as a minor fix of the syntax issue found on lines 336 and 337. But then, I added some more fixes:
* Option listings use the recommended definition list format instead of the regular bullet list.
* Some values in the YAML code listings have been wrapped in quotes. Otherwise, they completely disable YAML syntax highlighting.

Fixes and tweaks for the documentation

---

.travis.yml
DependencyInjection/DoctrineExtension.php
Resources/config/dbal.xml
Resources/config/orm.xml
Tests/DataCollector/DoctrineDataCollectorTest.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/DoctrineExtensionTest.php
composer.json
phpunit.xml.dist

This PR removes the deprecation notices when using DoctrineBundle with the upcoming Symfony 2.7.
ping @Ocramius

made the factories compatible with all Symfony versions (2.3 to 2.7)

---

DoctrineBundle.php

When shutting down the kernel, the connections should be closed to avoid leaking connections during tests, which could reach the connection limit. The entity managers should also cleared to give more chances to entities to be garbage collected.
Closes https://github.com/Behat/Symfony2Extension/issues/52

Close connections and clear managers on shutdown

---

DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/DoctrineExtensionTest.php

This gives a better error message than the one reported in #395 when doing invalid configuration of the bundle.

Add an exception when the ORM layer is configured but not DBAL

---

DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php

This can be particularly problematic in consumers as it gets Stopwatch injected.
Loggers can usually be flushed and so you can avoid leaking memory, but with Stopwatch it's not possible.

Enabling profiling should not automatically enable logging

---

Command/CreateDatabaseDoctrineCommand.php
Command/DropDatabaseDoctrineCommand.php

`listDatabases()` returns the unquoted database names and therefore
the command must use the unquoted database name for comparison

Compare with dbname with existing databases needs unquoted dbname

---

DependencyInjection/Compiler/EntityListenerPass.php
DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/orm_attach_entity_listener_tag.xml
Tests/DependencyInjection/Fixtures/config/yml/orm_attach_entity_listener_tag.yml

Adds support for tagging entity listeners, defining entity and method. 
Every listener service is created when the entitymanager is created for now. A solution could be marking the services lazy as suggested by @Ocramius and @Stof in https://github.com/doctrine/DoctrineBundle/issues/223

Added support for tagging entity listeners, without the need to map the listener

---

README.md

I'm pretty sure information about Symfony 2.0 and 2.1 is unnecessary anymore. Nor do i think we need to explain why the DoctrineBundle was pulled out of core.

remove old and unnecessary preamble from the README

---

Resources/views/Collector/db.html.twig

fixing the error 
Key "default" for array with keys "" does not exist in @Doctrine/Collector/db.html.twig at line 209

db profiller template fix

---

Resources/views/Collector/explain.html.twig

Postgres does not return a table for the explanation but a list of lines displaying the explanation in a formatted text.
The switch between the formats is based on whether each result row contains several columns (table formatting) or a single column (text formatting)

Improve the rendering of the query explanation for Postgres

---

DependencyInjection/DoctrineExtension.php

The dir parameter does not take arrays.

Removed non-working example

---

Command/GenerateEntitiesDoctrineCommand.php
Command/ImportMappingDoctrineCommand.php
Command/Proxy/RunDqlDoctrineCommand.php
Command/Proxy/RunSqlDoctrineCommand.php

Important for Symfony 3.0 where the console is not in `app/` anymore.

fixed hardcoded app/console

---

Resources/views/Collector/db.html.twig

there was a mistake I missed in #468. One of the changed reference was not a template name, but a controller reference /cc @fabpot

Fix the controller reference to explain queries

---

Resources/config/dbal.xml

In https://github.com/symfony/symfony/pull/16023 we're tweaking the priorities of the toolbar/profiler panels. The `265` value is the right number for Doctrine ... but maybe you don't want to merge it yet because this will change a lot the position of the Doctrine panel in the profiler/toolbar of Symfony versions older than 2.8.

Tweaked collector priority

---

DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php

[Since january](https://github.com/doctrine/doctrine2/commit/437f812) the `ResolveTargetEntityListener` implements the `EventSubscriber`-interface, but the concrete listener instance is still registered as simple listener listening on `loadClassMetadata`. This makes the listener miss the `onClassMetadataNotFound`. 
The concrete problem I have is, that I want setup all repositories in my DIC like this
```xml
<?xml version="1.0" ?>
<container xmlns="http://symfony.com/schema/dic/services"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
<services>
<service" id="user.manager" class="Doctrine\Common\Persistence\ObjectManager" public="false>
<factory service="doctrine" …
```

Register ResolveTargetEntityListener as subscriber

---

Resources/views/Collector/db.html.twig
Twig/DoctrineExtension.php

Refactored the doctrine_pretty_query filter to support "highlight only" mode

---

Command/CreateDatabaseDoctrineCommand.php

First of all: This may be a [DBAL-issue](https://github.com/doctrine/dbal).
However, when I specify the database connection via URL like `mysql://foo:bar@localhost/dbname` the command `doctrine:data:create` fails with an exception. I was able to extract the original exception from the driver (see below). It works, when I omit `dbname` from the URL and set it directly with the `dbname` configuration key.
```
#0 /vagrant/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection::__construct('mysql:host=127....', 'root', 'root', Array)
#1 /vagrant/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'root', Array)
#2 /vagrant/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php …
```

create:database fails, when dbname is set via URL

---

Command/CreateDatabaseDoctrineCommand.php

Fix creating sqlite database

---

Resources/views/Collector/db.html.twig

Fix https://github.com/symfony/symfony/issues/16976.
However, the item will also be hidden from the toolbar when using the old profiler/toolbar theme. 
I don't think it matters, but tell me if I'm wrong.

Fix ghost item in toolbar when no query

---

Controller/ProfilerController.php

See #500 #501
Didn’t want to wait so created a new PR myself.

Implement ContainerAwareInterface in ProfilerController

---

DependencyInjection/Configuration.php
Resources/config/schema/doctrine-1.0.xsd
Resources/doc/configuration.rst
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/dbal_service_multiple_connections.xml
Tests/DependencyInjection/Fixtures/config/yml/dbal_service_multiple_connections.yml

This PR is dependant upon doctrine/dbal#919.
PostgreSQL allows the user to set the sslrootcert is connecting
to database.

Add support to set PostgreSQL sslrootcert

---

DependencyInjection/Configuration.php
Resources/config/schema/doctrine-1.0.xsd

This PR is dependant upon https://github.com/doctrine/dbal/pull/798 .
PostgreSQL allows the user to set the application_name is connecting
to database. It is useful for monitoring purposes.
Currently one could just manually add 'application_name=foo' to DSN
by appending it to dbname, like:
> dbname:   %database_name% application_name=foo
It works but having a parameter eases setting it.

Add support to set PostgreSQL application_name

---

Resources/views/Collector/db.html.twig

Hi,
This PR fix the count break on the query list for count > 100.
*Before*
*After*

Fix count break on queries list for profiler

---

Resources/views/Collector/db.html.twig

As the toolbar is not displayed any more on top of the profiler with Symfony 3.x, we don't have direct information about:
- the count of database queries
- the global query time
- the count of invalid entities
I think this information could be displayed on top of the page as global query metrics, like global metrics on other pages in the Web Profiler.

Add global metrics on top of Doctrine page

---

DependencyInjection/DoctrineExtension.php
Tests/ContainerTest.php
composer.json

Allow to extract metadata about properties coming from Doctrine using the new PropertyInfo component of Symfony 2.8.

Register the PropertyInfo extractor from the Symfony Bridge

---

Command/CreateDatabaseDoctrineCommand.php
Command/DoctrineCommand.php
Command/DropDatabaseDoctrineCommand.php
Command/ImportMappingDoctrineCommand.php
DependencyInjection/Configuration.php
DependencyInjection/DoctrineExtension.php
Tests/Command/CreateDatabaseDoctrineTest.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/DoctrineExtensionTest.php

I need to use shard connections in my project, but it seems that some code is not up to date with sharding. This PR add some compatibility & options with shard connections.

Add --shard option to doctrine commands

---

Resources/doc/configuration.rst

If I'm reading https://github.com/doctrine/cache/pull/115 correctly apcu is now fully supported.  I updated the listing of provider to indicate this.
Since the default configuration of apcu in PHP 7 no longer provides backwards compatibility with apc API I also changed the example `metadata_cache_driver` to be `apcu` to be copy / paste ready for new deployments.

Add apcu configuration option in docs

---

Resources/config/orm.xml
composer.json

Related to https://github.com/symfony/symfony/pull/19203

Set doctrine.orm.entity_manager.abstract as lazy

---

Tests/Twig/DoctrineExtensionTest.php
Twig/DoctrineExtension.php

If paramters start with index 1 (as for sqlserver) the parameters should be interpolated correctly as well.
I am not absolutly shure, but i think they start always with index 1.

Fix interpolate query paramters if starting with index 1

---

DependencyInjection/DoctrineExtension.php

Without this change, and when doctrine/orm is not installed, you get a weird error message about the Version class that does not exist.

Add a proper exception when Doctrine ORM is not installed

---

Resources/doc/entity-listeners.rst

Took me a while to figure out you have to define the entity listener as
annotation as well.

Add entity annotation sample

---

Tests/Twig/DoctrineExtensionTest.php
Twig/DoctrineExtension.php

Escape binary string according to ODBC standard.
**Before:**
**After:**

Added binary escaping

---

DataCollector/DoctrineDataCollector.php
Resources/views/Collector/db.html.twig

DoctrineBundle is great at giving a quick heads-up when the application might benefit from optimizing the database queries.
But sometimes _it isn't easy to find what exactly to optimize,_ as there may be hundreds of queries. Are there a few very slow queries, or is there a bunch of quick ones that just add up? It's not easy to check at a glance which ones are the most expensive.
If only the profiler could group similar queries...
...finding the culprits would be much easier:
There, it's much easier to see that 4 different queries take up 80% of execution time.
---
I've considered other alternatives for getting quick insights into which queries to optimize first, when there's a need for that.
1. There's the [sensiolabs/doctrine-query-statistics-bundle](https://github.com/sensiolabs/SensioLa …

Add ability to group similar queries in Profiler.

---

Tests/RegistryTest.php

The implementation of the ManagerRegistry resetService started
using another method of the Container interface that wasn't mocked
and it broke the tests. The initialized method.
This PR just mock that method in the relevant tests.

Fix a test that wasn't mocking enough

---

DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/DoctrineExtensionTest.php

Making entity manager's second_level_cache.factory option work.
Simplified my fork compared to [initial attempt](https://github.com/doctrine/DoctrineBundle/pull/596). Not doing anything extra now, just factory parameter in the old place.
Longer explanation as requested by @stof:
Some pre-history in stackoverflow (no answers received): [SO link](http://stackoverflow.com/questions/40386291/provide-doctrine-with-custom-cache-factory-for-second-level-cache)
We have found no sensible way to set a custom factory via configuration. I may be blind, but I could not find any handling of manager's second_level_cache.factory option in extension class. So I am trying to make it work via changes requested.
I can see a possible issue that it won't work if someone's implementation of CacheFactory will …

Updating DoctrineExtension.php

---

Registry.php

The Symfony convention is to silence the deprecations to avoid issues with error handlers turning PHP errors into exceptions. But these deprecations were written before Symfony decided to use silenced warnings, and were not updated after that.

Update the deprecation warning convention

---

DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/orm_attach_entity_listeners_two_connections.xml
Tests/DependencyInjection/Fixtures/config/yml/orm_attach_entity_listeners_two_connections.yml

With multiple connections in `config.yml`
```
doctrine:
dbal:
default_connection: default
connections:
default:
...
foobar:
...
orm:
default_entity_manager: default
entity_managers:
default:
connection: default
foobar:
connection: foobar
```
each `EntityManager` will have multiple instances of `AttachEntityListeners` subscribed to the same event.

Avoid duplication of AttachEntityListeners

---

composer.json

Since https://github.com/doctrine/DoctrineBundle/commit/e2ca576ce35a16a0cf4e300068a4a5a5b54e36c7 the Twig extension makes use of `\Twig_SimpleFilter`, but the class does not exist before Twig 1.12 (not 1.10 nor 1.11).

Fix twig requirement constraint

---

DependencyInjection/Configuration.php
Resources/config/schema/doctrine-1.0.xsd
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/orm_service_simple_single_entity_manager_redis.xml
Tests/DependencyInjection/Fixtures/config/yml/orm_service_simple_single_entity_manager_redis.yml
composer.json

This work allow to select database configuration for redis cache driver for instance.
It completes https://github.com/doctrine/DoctrineCacheBundle/issues/46 and "finish" started work https://github.com/doctrine/DoctrineBundle/pull/393

Allow database entry for orm cache driver node config

---

ConnectionFactory.php

The responsability of changing the value of the initialized
property shouldn't be on the user of the initializeType method.

Separating concerns

---

DoctrineBundle.php

The command is just a proxy to dbal:import and does not depend on Docrine ORM.
So we can include it without ORM installed.

Enable doctrine:database:import command without ORM installed

---

ConnectionFactory.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/dbal_types.xml
Tests/DependencyInjection/Fixtures/config/yml/dbal_types.yml
Tests/TestCase.php

They were not marked as such if the mappingType array was
empty.
Sadly I don't see any way to test this right now.

Fix an issue were some commented type

---

DependencyInjection/DoctrineExtension.php
Resources/config/dbal.xml
Resources/config/orm.xml

Unnecessary since b66eac5a867db201a7ee49e0c35e97403fa9de39

Remove legacy code from DoctrineExtension

---

DependencyInjection/DoctrineExtension.php

Unnecessary since https://github.com/doctrine/DoctrineBundle/pull/581/commits/60ab71be6af053c3fc84e7908a0a6cd340c64547

Remove legacy mysql charset code from DI

---

Command/ImportMappingDoctrineCommand.php

Passing a string (Specifically 'ERROR') to the method writeln, which accepting int.
This causes exception "A non-numeric value encountered" in PHP 7.1

Fix exception "A non-numeric value encountered" in PHP 7.1

---

composer.json

Symfony master is now 4.0. This PR upgrades `composer.json` accordingly.

Allow Symfony 4.0

---

.travis.yml
DependencyInjection/DoctrineExtension.php
Tests/BundleTest.php
Tests/Command/CreateDatabaseDoctrineTest.php
Tests/ContainerTest.php
Tests/DataCollector/DoctrineDataCollectorTest.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/DoctrineExtensionTest.php
Tests/DependencyInjection/XMLSchemaTest.php
Tests/Mapping/ContainerAwareEntityListenerResolverTest.php
Tests/Mapping/DisconnectedMetadataFactoryTest.php
Tests/RegistryTest.php
Tests/TestCase.php
Tests/Twig/DoctrineExtensionTest.php
composer.json

As with ORM itself, the bundle will require PHP 7 in the future. Older Symfony versions may be removed in a separate pull request. I haven't made the effort to use the `::class` constant and short array syntax throughout, I'll leave that for a separate pull request.

Require PHP 7

---

ConnectionFactory.php
Tests/ConnectionFactoryTest.php
composer.json

The error occures if doctrine needs to establish a connection to
determine the platform version to register the types.
The idea is to provide some more information so the user can
understand what and why this is happening.
This is discussed at:
https://github.com/doctrine/DoctrineBundle/issues/673

Enhance exception message

---

Resources/views/Collector/db.html.twig

Table which is shown in Weprofiler is not clean while values in sql explain table are long.
This PR adds horizontal scroll for long tables. 
**Related PR in Symfony Webprofiler:** https://github.com/symfony/symfony/pull/23706
_(It does not cause any backward compatibility problems)_
**Before:**
**After:**

[Webprofiler] Improve SQL explain table display

---

Resources/config/dbal.xml
Tests/DependencyInjection/DoctrineExtensionTest.php

Although this is a class rather than an interface, it is the main API of Doctrine DBAL, which has more helper methods than the driver connection interface. So using it in typehints make sense when using these helpers.

Add autowiring for Doctrine\DBAL\Connection

---

DependencyInjection/DoctrineExtension.php
composer.json

Not sure if master is the correct branch as this will prevent any non-7.1 user from benefiting from this.
This will leverage the new 3.4 "kernel.reset" tag to reset the cache in DoctrineEntity (parent of EntityClass).
Thus making kernel-in-a-loop better (see https://github.com/symfony/symfony/issues/23984).
Works with https://github.com/symfony/symfony/pull/24232

Add "kernel.reset" tag to "form.type.entity"

---

DependencyInjection/DoctrineExtension.php

That's required as those services are retrieved with `container->get()`, so they must be public as of Symfony 4 (but there are private by default).

Change services to be public for compat with Symfony 4

---

DoctrineBundle.php

Form SF 3.0 IntrospectableContainerInterface merged with ContainerInterface
SF < 3.0 `initialized` in IntrospectableContainerInterface
SF > 3.0 `initialized` in ContainerInterface

Fixed for SF > 3.0 on shutdown container create and close connections

---

DependencyInjection/Compiler/EntityListenerPass.php
DependencyInjection/DoctrineExtension.php
Registry.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php

Sibling to https://github.com/symfony/symfony/pull/24409
I chose to made as less changes as possible and not create a PSR-11 service locator in a patch release.

Fix deprecation with Symfony 3.4

---

Controller/ProfilerController.php

Fixes #707
Should be backported to 1.6.x too.

Fix profiler query explaining without the templating component

---

DependencyInjection/DoctrineExtension.php
Resources/config/dbal.xml
Tests/DependencyInjection/DoctrineExtensionTest.php

As used by [Symfony's `ControllerTrait`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php#L418-L422), make the `doctrine` service public.

`doctrine` service is public

---

DoctrineBundle.php
Resources/config/dbal.xml
Resources/config/orm.xml

Commands auto-registration is deprecated in Symfony 3.4. This PR will avoid `Auto-registration of the command "Doctrine\Bundle\DoctrineCacheBundle\Command\xxx" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead.` exceptions.

Fix Symfony 3.4 auto-registration deprecation

---

Tests/ConnectionFactoryTest.php

Hi guys!
While trying to mock the DriverInterface directly, PhpUnit throws:
> Class cannot implement interface Throwable
from the mocked class. I believe this is just a nice workaround. But if there's a more proper way to fix it, let me know!
Thanks!

Fixing master tests

---

.travis.yml
DependencyInjection/DoctrineExtension.php
Tests/ConnectionFactoryTest.php
Tests/DataCollector/DoctrineDataCollectorTest.php
Tests/Mapping/DisconnectedMetadataFactoryTest.php
Tests/RegistryTest.php
composer.json

Hi guys!
This bundle was bumped to PHP 7.1 only, but the next version of Symfony (3.4) will still support 5.5. This inconsistency makes the latest version of this bundle not usable by some users (including Ubuntu LTS). This re-adds PHP 5 support without breaking BC.
I believe Fabien (https://github.com/doctrine/DoctrineBundle/pull/725#issuecomment-339421794) is also in favor of this - I don't think it makes sense to bump the version yet, especially when this bundle really isn't using any PHP 7 features.
Thanks!

Reverts the bump from PHP 5 to PHP 7.1: re-adds php 5.5 support

---

Resources/config/dbal.xml
Resources/config/orm.xml
Tests/DependencyInjection/DoctrineExtensionTest.php

#640 added a bunch of aliases for autowiring, but some of them don't make sense because the interfaces might also be implemented by other bundles. Thus, interfaces in `Doctrine\Common` shouldn't be used as service aliases for ORM-specific implementations.
For example, this conflicts with https://github.com/doctrine/DoctrineMongoDBBundle/pull/441 - in order to not confuse people I believe it's best if none of the mappers registers service aliases for the common interfaces.

Remove aliases for common interfaces

---

Tests/ServiceRepositoryTest.php
Tests/TestCase.php

Some of the tests on master are failing. They're not a big: in `ContainerTest`, we're fetching every service we created and checking its type. That's a very pragmatic test, but doesn't work when services become private. For this one test, I've made all services public. This is a fairly common tactic in tests for Symfony bundles. And, it should make the tests happy again :).
Cheers!

Fixing ContainerTest where we try to fetch private services

---

Command/GenerateEntitiesDoctrineCommand.php

Since the Doctrine devs aren't interested in maintaining the generation commands and since we implemented them in MakerBundle, I hope this will be a nice win for everyone: let's point them elsewhere and avoid issues being created related to Symfony 4 support :).

Deprecating doctrine:generate:entities and pointing to MakerBundle

---

Command/ImportMappingDoctrineCommand.php
Tests/Command/ImportMappingDoctrineCommandTest.php
composer.json

Hi guys!
This replaces and builds off of #779, which fixes #736.
It's VERY simple: the first argument can now be a bundle (like before) or a namespace:
A) If it's a bundle, everything works 100% like before.
B) If it's *not* a bundle, we assume it's the namespace. Then, there's no magic: we require them to explicitly pass us the path where the files should be generated. No fancy guess work.
Unfortunately, this is very difficult to test. So, I've purposefully made the diff very light and consistent. I've tested this in a REAL app, by copying the first 3 examples in the `setHelp()` to test everything. It all works perfectly.
Thanks!

Fix doctrine:mapping:import to work in Symfony 4 (no bundle)

---

DataCollector/DoctrineDataCollector.php
Tests/DataCollector/DoctrineDataCollectorTest.php

Right now the collector keep grouped queries even you create new collector instance and it's wrong.

Clear grouped queries on each collect

---

ManagerConfigurator.php
composer.json

Let ManagerConfigurator use EntityManagerInterface instead of EntityManager, so you can use custom EntityManager implementations by extending EntityManagerDecorator.   
BC-Break: that raises the `doctrine/orm` requirement from `~2.3` to `~2.4`.

Use EntityManagerInterface

---

Resources/config/dbal.xml
Resources/config/orm.xml
Tests/DependencyInjection/DoctrineExtensionTest.php

Revert "Remove aliases for common interfaces"

---

Controller/ProfilerController.php

Recent Symfony versions are wrapping the params in a VarDumper Data when collecting the profiler info. This ensures that they get unwrapped properly when trying to explain the query.
Fixes #757

Fix explaining queries

---

Command/CreateDatabaseDoctrineCommand.php
Command/DropDatabaseDoctrineCommand.php
Tests/Command/DropDatabaseDoctrineTest.php

Please review commit by commit.
Could be squashed after review into one.
Before:
this is wrong, as my DB is `luna` and my connection is `default`
After:

Refactor commands to avoid wrong output

---

DependencyInjection/Configuration.php
Resources/config/schema/doctrine-1.0.xsd
Resources/doc/configuration.rst
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/dbal_service_multiple_connections.xml
Tests/DependencyInjection/Fixtures/config/yml/dbal_service_multiple_connections.yml

Hi all,
In doctrine/dbal v2.6, was introduced a parameter default_dbname for postgre driver.
The bundle do not have the configuration option availaible so here is a PR.
I'm new to contributing on doctrine so I'm open to any suggestions.

Add missing default_dbname configuration option

---

Resources/doc/entity-listeners.rst

Question:  Is `src/EventListener` the recommended location for an entity listener?
This integrates the findings of @piotrekkr at https://github.com/symfony/symfony-docs/issues/5013  
Since all basics are now covered, I'd say you can close the issue.

Complete example

---

.travis.yml
DependencyInjection/Compiler/MessengerPass.php
DependencyInjection/DoctrineExtension.php
DoctrineBundle.php
Resources/config/messenger.xml
Tests/DependencyInjection/Compiler/MessengerPassTest.php
Tests/DependencyInjection/DoctrineExtensionTest.php
composer.json

Relates to https://github.com/symfony/symfony/pull/27128
How should we process for the CI?

[Messenger] Wire the transaction middleware factory when component is enabled

---

Repository/ContainerRepositoryFactory.php
Tests/Repository/ContainerRepositoryFactoryTest.php

A verification was done with EntityRepository inheritance. This commit drop it in favor of a check on interface ObjectRepository which allow the user to define its own complete repository.
Closes https://github.com/doctrine/DoctrineBundle/issues/856

Support user defined repositories

---

DependencyInjection/Compiler/EntityListenerPass.php

Discussed in https://github.com/symfony/symfony/issues/28304#issuecomment-422710505
When an entity listener is declared as lazy at the definition level (and not at the tag level), then it is registered using the `ContainerAwareEntityListenerResolver::register()`. This class in turn uses `get_class()` to create its internal map.
But `get_class()` on a lazy-proxy returns the generated class of the proxy - not the class of the listener implementation.
Makes sense?

Fix handling of lazy entity listeners

---

DependencyInjection/Configuration.php

Fix PHP 5.6+only syntax that breaks the Symfony CI

---

README.md

Enhancement: Use SVG badge for Travis CI build status

---

.travis.yml
DependencyInjection/Configuration.php
DependencyInjection/DoctrineExtension.php
Tests/ContainerTest.php
Tests/ProfilerTest.php

Fix tests, and improve Symfony 4.2 compat

Fix Symfony 4.2 deprecations, and Travis build

---

DependencyInjection/Configuration.php
Resources/config/schema/doctrine-1.0.xsd
Resources/doc/configuration.rst
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/dbal_service_multiple_connections.xml
Tests/DependencyInjection/Fixtures/config/yml/dbal_service_multiple_connections.yml

I was trying to setup an SSL connection to a PostgreSQL database, using the pdo_pgsql driver. According to [the documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/configuration.html#pdo-pgsql), the following SSL options should be supported:
* sslmode
* sslrootcert 
* sslcert
* sslkey
* sslcrl
Although, when setting the configuration as such (with the given parameters set in parameters.yml file):
```
doctrine:
dbal:
sslmode: 'verify-ca'
sslrootcert: '%database_sslrootcert_path%'
sslcert: '%database_sslcert_path%'
sslkey: '%database_sslkey_path%'
```
I would get the following exception from the Symfony Config component:
```
In ArrayNode.php line 311:
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]     
Unrecognized options …
```

Add PostgreSQL SSL options support

---

Command/CreateDatabaseDoctrineCommand.php
Command/DoctrineCommand.php
Command/DropDatabaseDoctrineCommand.php
Command/GenerateEntitiesDoctrineCommand.php
Command/ImportMappingDoctrineCommand.php
Repository/ServiceEntityRepository.php
Resources/config/dbal.xml
Resources/config/orm.xml
Tests/Command/CreateDatabaseDoctrineTest.php
Tests/Command/DropDatabaseDoctrineTest.php
Tests/ContainerTest.php

Follows (and needs) #876.
It works, but it introduces several BC breaks:
* Commands doesn't extend `ContainerAwareCommand` anymore (as this class is deprecated)
* Some constructor parameters are now mandatory (because we use DI instead of injection the container)
Making the commands fully BC would be possible by using hacks like [this one](https://github.com/symfony/panther/blob/master/src/PantherTestCase.php#L19-L29) to introduce some conditional inheritance, but I'm not sure that it is worth it: `ContainerAwareCommand` commands were designed to be initialized by the framework itself.
Also, to prevent future similar issues, I marked these commands `@final`, and the abstract `DoctrineCommand` as `@internal`.

 Port commands for Symfony 4.2 (follows #876)

---

Command/CreateDatabaseDoctrineCommand.php
Tests/Command/CreateDatabaseDoctrineTest.php

Creating a new database for the global database of a sharded configuration fails, because the command tries to connect to the database that doesn't exist yet.
The cause of this is that the dbname, url and path parameters are not unset for sharded databases, while they are unset for 'normal' connections.

Unset parameters for sharded databases as well

---

DependencyInjection/Configuration.php
Tests/DependencyInjection/ConfigurationTest.php

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Fixed tickets | https://github.com/symfony/symfony/issues/29390
Hi there is a **ReflectionException Class Doctrine\Common\Proxy\AbstractProxyFactory does not exist** when the `DoctrineBundle` is used without `doctrine/common` being installed. 
Consider this scenario
1. Here are deps in the `composer.json` of my project:
```php
"require": {
"php": "^7.1.3",
"ext-ctype": "*",
"ext-iconv": "*",
"symfony/console": "4.2.*",
"symfony/flex": "^1.1",
"symfony/framework-bundle": "4.2.*",
"symfony/yaml": "4.2.*"
},
```
2. I install `DoctrineBundle` with `require doctrine/doctrine-bundle`.
3. I activate `DoctrineBundle` in `Kernel`. This entails **ReflectionException Class …

Fix exception when configuration is used without doctrine/orm nor doctrine/common

---

Resources/doc/entity-listeners.rst

The `lazy` tag attribute was not mentioned in the docs.
This might be superfluous in case https://github.com/doctrine/DoctrineBundle/issues/899 can/will be done

[Documentation][Entity Listeners] Mention lazy tag attribute

---

Resources/doc/entity-listeners.rst

The code example is weirdly misleading because the same class is attached to the `preUpdate` event twice. Furthermore, the YAML example is wrong and inconsistent with the XML example. This PR fixes that.

Update examples in entity listeners documentation

---

DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/dbal_service_pool_sharding_connection.xml
Tests/DependencyInjection/Fixtures/config/xml/dbal_service_single_master_slave_connection.xml
Tests/DependencyInjection/Fixtures/config/yml/dbal_service_pool_sharding_connection.yml
Tests/DependencyInjection/Fixtures/config/yml/dbal_service_single_master_slave_connection.yml

Fixes #900. Supersedes #901.
The schema tool always reads `defaultTableOptions` from the root options, so we may not move it to the `global` or `master` sub-array in sharded or master/slave connections.

Don't rewrite defaultTableOptions in sharded or master/slave connections

---

Resources/doc/configuration.rst

This problem was spotted by @nicolas-grekas. He suggested to use instead the same value as in the official recipe (https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/manifest.json). I fully agree with that and I hope you do too. Thanks.

Updated the value of path option to match the official recipe

---

Resources/doc/entity-listeners.rst

Hello,
Entity listener documentation was giving different syntaxes, without explaining was was required exactly and for which versions to use those. It was hard to understand the entity annotation is required if you use the "short" service definition, or that you can use the "long" comprehensive service definition in place.
It was misleading for new users, and even for senior ones, I got it wrong today.
This change proposal hopes to make it clearer, but explaining the 2 different syntaxes one after the other.

Made entity listener documentation less ambiguous

---

Resources/doc/configuration.rst

In https://symfony.com/doc/current/bundles/DoctrineBundle/configuration.html#doctrine-dbal-configuration you can see that the XML config doesn't show highlighted contents. This PR may fix it.

Added some missing contents to an XML config sample

---

Tests/ProfilerTest.php
Twig/DoctrineExtension.php
composer.json

Use namespaced Twig

---

Registry.php

Follow up of https://github.com/doctrine/DoctrineBundle/pull/892

Drop support for Symfony < 3.4

---

Controller/ProfilerController.php
DataCollector/DoctrineDataCollector.php
Tests/Repository/ContainerRepositoryFactoryTest.php
Twig/DoctrineExtension.php
composer.json

Changed `doctrine/coding-standard` in `composer.json` to `6.0`  and fixed found issues via `phpcbf`

Updated doctrine/coding-standard to 6.0

---

.travis.yml

Twig deprecations were fixed in #929 but can't be fixed in 1.10 due to the change to twig requirements in composer.json. Thus, the build now allows three deprecations in general before failing the build.

[1.10] Don't fail build for the 3 known Twig deprecations

---

Command/DoctrineCommand.php

This adds previously removed deprecation notices (see #877) to DoctrineCommand. This helps people extending the command work around future BC breaks.

Add deprecation notices for container in DoctrineCommand

---

DependencyInjection/DoctrineExtension.php
Resources/config/messenger.xml

Supersedes #868.
This adds a service for the DoctrineTransportFactory class to the messenger integration config, but doesn't tag it as transport factory. This way, there shouldn't be any errors due to the class not being present in older versions of symfony/messenger.
The tag is then added in DoctrineExtension if the class in question actually exists.
I'm not sure how to best test this since all we're checking is whether the service has a tag; this information is no longer available in the compiled container. Any suggestions?

Wire messenger transport factory

---

Dbal/RegexSchemaAssetFilter.php
Dbal/SchemaAssetsFilterManager.php
DependencyInjection/Compiler/DbalSchemaFilterPass.php
DependencyInjection/DoctrineExtension.php
Resources/config/dbal.xml
Tests/Dbal/RegexSchemaAssetFilterTest.php
Tests/Dbal/SchemaAssetsFilterManagerTest.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/dbal_schema_filter.xml
Tests/DependencyInjection/Fixtures/config/yml/dbal_schema_filter.yml

Hi!
If you're using doctrine/dbal 2.9 or higher, this removes the deprecated call to `Configuration:: setFilterSchemaAssetsExpression()`. It also makes the "schema filter" extendable via a tag. The use-case is when a 3rd-party bundle manages a table automatically for you through DBAL and you don't want, for example, Doctrine migrations (https://github.com/doctrine/migrations/blob/cf7f94b0bcfbd7d9c240aee759dc6619bc9ad796/lib/Doctrine/Migrations/Generator/DiffGenerator.php#L117) / `doctrine:schema:update` to suggest removing that table because it's not found in the mapping metadata.
One real-world use-case will be for #868: when the Doctrine transport is added to Messenger, a table will be created for storing messages (either automatically by Messenger or manually by the user - their …

Removing deprecated call to Configuration::setSchemaAssetsFilter() + extendable

---

DependencyInjection/Configuration.php
DependencyInjection/DoctrineExtension.php
Resources/doc/configuration.rst
Tests/DependencyInjection/DoctrineExtensionTest.php
composer.json

This PR adds support for using a symfony/cache pool directly without having to create extra services. It makes the default configuration from the recipe a lot shorter:
```patch
doctrine:
orm:
auto_generate_proxy_classes: false
metadata_cache_driver:
-            type: service
-            id: doctrine.system_cache_provider
+            type: pool
+            pool: doctrine.system_cache_pool
query_cache_driver:
-            type: service
-            id: doctrine.system_cache_provider
+            type: pool
+            pool: doctrine.system_cache_pool
result_cache_driver:
-            type: service
-            id: doctrine.result_cache_provider
+            type: pool
+            pool: doctrine.result_cache_pool
-services:
-    doctrine.result_cache_provider:
-        class: …
```

Add symfony cache pool support

---

DependencyInjection/DoctrineExtension.php

fixes symfony/symfony#30948
#FOSSHackathons #EUFOSSA

abstain from registering incomplete services

---

DependencyInjection/Compiler/EntityListenerPass.php
Mapping/ContainerAwareEntityListenerResolver.php
Mapping/ContainerEntityListenerResolver.php
Resources/config/orm.xml
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/CustomEntityListenerServiceResolver.php
Tests/DependencyInjection/Fixtures/config/xml/orm_attach_lazy_entity_listener.xml
Tests/DependencyInjection/Fixtures/config/xml/orm_entity_listener_custom_resolver.xml
Tests/DependencyInjection/Fixtures/config/yml/orm_attach_lazy_entity_listener.yml
Tests/DependencyInjection/Fixtures/config/yml/orm_entity_listener_custom_resolver.yml
Tests/DependencyInjection/Fixtures/config/yml/orm_entity_listener_resolver.yml
Tests/Mapping/ContainerEntityListenerResolverTest.php

EUFOSSA
This implements https://github.com/doctrine/DoctrineBundle/issues/899
- rename `ContainerAwareEntityListenerResolver` into `ContainerEntityListenerResolver` + deprecate old class
- make entity listener services lazy by default (if no `lazy` tag attribute specified)
- use service locator as a smaller container for resolving services
I tested this on my huge work project which uses Symfony 3.4 and we have 3 entity listeners:
```
Information for Service "doctrine.orm.default_entity_listener_resolver"
=======================================================================
---------------- ------------------------------------------------------------------------ 
Option           Value                                                                   
---------------- …
```

Add ContainerEntityListenerResolver + load listeners lazy by default

---

ConnectionFactory.php
DependencyInjection/Configuration.php
Tests/ConnectionFactoryTest.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/TestCommentedType.php
Tests/TestCase.php
phpunit.xml.dist

Supersedes #628.
The `commented` attribute will be removed in 2.0. To allow people to migrate properly and not have to deal with deprecations until actually switching to 2.0, the default value of `commented` changes from `true` to `null` so we know whether a type was explicitly marked as commented or not. The connection factory now takes into account whether a type itself requires a comment and only explicitly marks it as commented if 
Depending on the scenario, appropriate deprecation notices will be thrown according to the table below:
| Type commented | No `commented` attribute | `commented: true` | `commented: false` |
| --- | --- | --- | --- |
| Yes | No change | Deprecation notice to remove attribute | Deprecation notice to remove attribute |
| No | Implicitly marked commented to …

Deprecate type comment attribute from configuration

---

Resources/config/schema/doctrine-1.0.xsd

#948 added support for the `pool` option in the cache configuration, but this was never added to the schema. This PR adds the `pool` option to the XSD.

Add new pool option to XSD

---

Resources/views/Collector/db.html.twig

Linkify backtrace callstack

---

UPGRADE-1.11.md
UPGRADE-2.0.md

This adds `UPGRADE-*` documentation as done for Symfony. UPGRADE-2.0 documents BC breaks that will happen in 2.0 by removing deprecated functionality.

Add upgrade files

---

DependencyInjection/DoctrineExtension.php

Thanks for publishing `1.11.0` version.
When updating to `1.11.0` and simplifying my previous hacky configuration by using the new method for declaring cache configuration based on the symfony cache pools, I got one error.
```
The service "doctrine.orm.default_entity_manager" has a dependency on a non-existent service "doctrine.orm.cache.pool.my_cache_pool".
```
By looking at the code, the `createPoolCacheDefinition` returns a service id, which will be aliased later, but this service id was never registered on the container (instead it was its alias).
I updated the code so that the service id is registered and could later be aliased.

Fix non existent service when using symfony cache pools

---

DoctrineBundle.php
Tests/BundleTest.php

Schema filters were broken on doctrine/dbal 2.9 and higher by https://github.com/doctrine/DoctrineBundle/pull/935. The compiler pass registration was missing.

Fix schema filters

---

DependencyInjection/DoctrineExtension.php

Wiring for symfony/symfony#31486.

Wiring of the new PropertyAccessExtractor

---

DependencyInjection/DoctrineExtension.php

Fixes BC break with mistakenly removed `kernel.reset` tag from `form.type.entity` service, because `DoctrineType` implements `ResetInterface` only in Symfony 4.2+, therefore all previous versions starting from 3.4 are affected.
This BC break was introduced in version 1.11.0 in commit 6b25ea4

Fix BC break with DoctrineType::reset() for all Symfony versions

---

Resources/config/messenger.xml
Tests/DependencyInjection/DoctrineExtensionTest.php

Follow up of https://github.com/symfony/symfony/pull/31334
Similar to https://github.com/doctrine/DoctrineBundle/pull/956

Register DoctrineClearEntityManagerMiddleware as a service

---

.travis.yml

This fixes an issue where coverage tests fail because of a deprecated class that is still used due to the older messenger version

Require latest version of symfony/messenger for coverage tests

---

Tests/DataCollector/DoctrineDataCollectorTest.php
Tests/ProfilerTest.php

With https://github.com/symfony/symfony/pull/32163, the `DoctrineDataCollector` class ensures the `types` property of the query is an array. However, in our tests where we use a mock of the DebugStack, we did not add any type information whatsoever, leading to an error in our tests.

Fix wrong query structure in tests

---

DependencyInjection/Compiler/EntityListenerPass.php
Resources/doc/entity-listeners.rst
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/InvokableEntityListener.php
Tests/DependencyInjection/Fixtures/config/xml/orm_attach_entity_listener_tag.xml
Tests/DependencyInjection/Fixtures/config/yml/orm_attach_entity_listener_tag.yml

It will allow to fall back on the `__invoke` method by default with no breaking change.

[EntityListener] Fallback on __invoke method if it exists

---

.travis.yml

We can't remove usage of that interface without breaking BC, so the tests running against Symfony 4.4 will have to ignore that single deprecation. The interface will be dropped from the class declaration for 2.0, along with the deprecated methods.

Ignore deprecation for RegistryInterface

---

Registry.php
Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomServiceRepoRepository.php
UPGRADE-2.0.md

Hot on the heels of #1000, this drops usage of the removed interface from the manager registry and drops methods that were deprecated in Symfony 2.

[2.0] No longer implement deprecated RegistryInterface

---

Command/DropDatabaseDoctrineCommand.php
Command/GenerateEntitiesDoctrineCommand.php
composer.json

See https://github.com/doctrine/DoctrineBundle/pull/1024#issuecomment-538668474

Require php-7.4-friendly version of Twig

---

Command/DoctrineCommand.php
Resources/config/dbal.xml

Since the master branch is 2.0 now, this code can be removed, right? 😃

Remove deprecated functionality from DoctrineCommand

---

DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/DoctrineExtensionTest.php

Based on #1010, but targeting 1.12.x with this PR. Credit goes to @unixslayer who did the original implementation.
I updated the integration test to ensure the configuration doesn't need the `orm` node to add the messenger integration.

Load messenger services independently from ORM layer

---

Repository/ServiceEntityRepository.php
Resources/config/dbal.xml
Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomServiceRepoRepository.php

This adds a new alias as a replacement for the deprecated `RegistryInterface` from the Doctrine Bridge.

Add new service alias for manager registry

---

Repository/ServiceEntityRepository.php
Resources/config/dbal.xml
Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomServiceRepoRepository.php
UPGRADE-2.0.md

Promoting autowiring aliases that target classes is encouraging ppl to create tight coupling with the implementation, while IoC is about coding against abstractions.
The fact that the interface is also implemented by the ODM is not an issue to me: this is just the default autowiring alias for the interface. It should serve the majority. There is no issue keeping it.
If we want two aliases, a latter PR could add named autowiring aliases.
Side note: the alias for `Doctrine\ORM\EntityManagerInterface` is encouraging type hinting against a stateful service. But that's for another PR :)

Restore autowiring alias for ManagerRegistry

---

DataCollector/DoctrineDataCollector.php
Resources/views/Collector/db.html.twig

This PR takes into account the new `runnable` flag that was added in collected data in https://github.com/symfony/symfony/pull/34384.

[DoctrineDataCollector] Handle runnable flag

---

Tests/ContainerTest.php
Tests/TestCase.php

This removes deprecations that get the build to fail: YAML mappings are deprecated in ORM 2.7

Use XMLBundle in container tests

---

Resources/config/orm.xml

Fixes #1057: introduces a new naming strategy that avoids the deprecation notice when using a number-unaware underscore naming strategy.

Add number-aware underscore naming strategy

---

ConnectionFactory.php
Tests/ConnectionFactoryTest.php
UPGRADE-2.0.md

Configuring charset in a portable way is a real pain for the community.
See e.g. https://github.com/symfony/recipes/pull/674, which triggered https://github.com/symfony/recipes/issues/689, then https://github.com/symfony/recipes/pull/691/files, but the situation is still not fixed.
This is the only way to fix the issue in a way that would make sense: use real-utf8 by default for all platforms (ie utf8mb4 on Mysql).
Here is the patch doing so, targeting 2.0.1.
I'd happily submit on 1.12 if you think that's possible.

Default to real-utf8 when no charset is provided

---

.travis.yml
composer.json

This fixes build issues due to some builds now installing Symfony 4.4 for some dependencies. It duplicates changes made to the travis-ci config in master.

Use symfony/flex to lock Symfony dependencies to the same version

---

Command/ImportMappingDoctrineCommand.php
UPGRADE-2.1.md

Follow-up from https://github.com/doctrine/DoctrineBundle/pull/1054

Deprecate doctrine:mapping:import

---

Repository/ContainerRepositoryFactory.php

This bundle required symfony 3.4+ now - therefore the container must not be optional anymore.

Make container in costructor of ContainerRepositoryFactory mandatory

---

Command/DoctrineCommand.php
Command/ImportMappingDoctrineCommand.php
Command/Proxy/DelegateCommand.php
DataCollector/DoctrineDataCollector.php
DependencyInjection/DoctrineExtension.php
Mapping/DisconnectedMetadataFactory.php
Repository/ContainerRepositoryFactory.php
Repository/ServiceEntityRepository.php
Resources/config/dbal.xml
Tests/Command/CreateDatabaseDoctrineTest.php
Tests/Command/DropDatabaseDoctrineTest.php
Tests/ConnectionFactoryTest.php
Tests/ContainerTest.php
Tests/DataCollector/DoctrineDataCollectorTest.php
Tests/DependencyInjection/DoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomServiceRepoRepository.php
Tests/Mapping/DisconnectedMetadataFactoryTest.php
Tests/ProfilerTest.php
Tests/Repository/ContainerRepositoryFactoryTest.php
Tests/Repository/ServiceEntityRepositoryTest.php
Tests/ServiceRepositoryTest.php
Tests/TestCase.php
composer.json

Rel: https://github.com/doctrine/orm/pull/7953, https://github.com/doctrine/persistence/pull/71
This will make our build after upmerging it clean.
Other than new Persistance deprecations, I have also fixed some extra ones I noticed, such as deprecated `Version` class (we always require ORM in require-dev, so in test cases I just removed its usage, otherwise I used UnitOfWork - EntityManagerInterface triggers deprecation)

Fix doctrine deprecations

---

DependencyInjection/Configuration.php
Resources/config/schema/doctrine-1.0.xsd
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/dbal_service_multiple_connections.xml
Tests/DependencyInjection/Fixtures/config/yml/dbal_service_multiple_connections.yml

DBAL actually accepts mixed[], not string[] as we force. This causes problems with some options, such as `userDefinedFunctions`.
Fixes #365

Allow non-scalar DBAL options

---

Registry.php
Resources/config/dbal.xml
composer.json

Fixes #1083.
This also adds a dependency to the Symfony Service contracts to ensure we've got the ResettableInterface.

Make manager registry resettable

---

Registry.php
Tests/RegistryTest.php

This fixes errors of the sort "InvalidArgumentException: Doctrine ORM Manager named "doctrine.orm.default_entity_manager" does not exist."

Fix error when resetting manager registry

---

.github/stale.yml

I'm strongly opposed to adding bot which automatically closes issues without human involvement, but here it's configured to require certain label first, so it's involvement will be here only in cases we manually mark as such.
Idea here is to post warning in issues labelled as "Status: Waiting feedback"
if there is no activity after 14 days and after no further activity within 7 days happen, closes it.

Activate selective stale probot

---

Registry.php
Tests/RegistryTest.php

See https://github.com/doctrine/DoctrineBundle/pull/1106#issuecomment-567178319.
This refines the logic for resetting managers on `kernel.reset`:
* Lazy managers will be reset through `resetManager`
* Non-lazy managers will be cleared using `EntityManager::clear`
* Uninitialised managers will be ignored
Also adds tests for all use-cases.
@ro0NL can you give this a test and see if it works? As much as I love releasing with our new tools, I'm afraid I'll run out of release numbers by the time this is fixed 😂

Fix resetting non-lazy managers

---

.github/stale.yml

Issues that are added to a milestone or a project should not be marked as stale, despite the feedback label.

Don't mark milestoned issues as stale

---

Tests/BundleTest.php
Tests/Command/CreateDatabaseDoctrineTest.php
Tests/Command/DropDatabaseDoctrineTest.php
Tests/Command/ImportMappingDoctrineCommandTest.php
Tests/ConnectionFactoryTest.php
Tests/ContainerTest.php
Tests/DataCollector/DoctrineDataCollectorTest.php
Tests/Dbal/RegexSchemaAssetFilterTest.php
Tests/Dbal/SchemaAssetsFilterManagerTest.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/DependencyInjection/DoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/CustomEntityListenerServiceResolver.php
Tests/DependencyInjection/TestFilter.php
Tests/DependencyInjection/XMLSchemaTest.php
Tests/DependencyInjection/XmlDoctrineExtensionTest.php
Tests/DependencyInjection/YamlDoctrineExtensionTest.php
Tests/Mapping/ContainerEntityListenerResolverTest.php
Tests/Mapping/DisconnectedMetadataFactoryTest.php
Tests/ProfilerTest.php
Tests/RegistryTest.php
Tests/Repository/ContainerRepositoryFactoryTest.php
Tests/Repository/ServiceEntityRepositoryTest.php
Tests/ServiceRepositoryTest.php
Tests/TestCase.php
Tests/Twig/DoctrineExtensionTest.php

As a side effect, this makes the code a bit more forward-compatible with
recent versions of PHPUnit, that have that return type declaration on
setUp().

Add void return type declaration to tests

---

ConnectionFactory.php
Controller/ProfilerController.php
DependencyInjection/Compiler/EntityListenerPass.php
DependencyInjection/Compiler/ServiceRepositoryCompilerPass.php
DependencyInjection/Configuration.php
DependencyInjection/DoctrineExtension.php
ManagerConfigurator.php
Mapping/DisconnectedMetadataFactory.php
Repository/ContainerRepositoryFactory.php
Tests/Builder/BundleConfigurationBuilder.php
Tests/Command/CreateDatabaseDoctrineTest.php
Tests/Command/DropDatabaseDoctrineTest.php
Tests/ConnectionFactoryTest.php
Tests/DataCollector/DoctrineDataCollectorTest.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/DoctrineExtensionTest.php
Tests/DependencyInjection/TestDatetimeFunction.php
Tests/DependencyInjection/TestNumericFunction.php
Tests/DependencyInjection/TestStringFunction.php
Tests/DependencyInjection/TestType.php
Tests/DependencyInjection/XmlDoctrineExtensionTest.php
Tests/DependencyInjection/YamlDoctrineExtensionTest.php
Tests/Repository/ContainerRepositoryFactoryTest.php
Tests/TestCase.php
Tests/Twig/DoctrineExtensionTest.php
Twig/DoctrineExtension.php

That means:
- methods in final classes
- final methods (none of those found)
- private methods
- methods in Tests (that excludes `setUp()`, `tearDown()` and `test*`, which
are handled with an automated tool in #1121 )

Add type declarations where backwards compatible

---

DependencyInjection/DoctrineExtension.php
EventSubscriber/EventSubscriberInterface.php

Added EventSubscriberInterface marker interface to support autoconfiguration

---

Registry.php
Tests/Command/ImportMappingDoctrineCommandTest.php
Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestCustomClassRepoRepository.php
Tests/DependencyInjection/Fixtures/TestKernel.php
Tests/RegistryTest.php
composer.json

Fixes #1114
We can't reset because of this https://github.com/symfony/symfony/issues/35216 + performance issues, so let's just do clear() so it works for long running processes (same thing php-pm does for years).

Fix desynchronized entity managers after kernel reset

---

Repository/ContainerRepositoryFactory.php

The container is always set

---

Command/CreateDatabaseDoctrineCommand.php
Command/DropDatabaseDoctrineCommand.php
Tests/Command/CreateDatabaseDoctrineTest.php
Tests/Command/DropDatabaseDoctrineTest.php

Hi everyone 👋 
As notified here: https://github.com/doctrine/DoctrineBundle/issues/1072, here's the PR for the commands shortcuts, I need to finish the tests (on commands that don't have ones for now). 
Feel free to give feedback 🙂

[FEAT] Commands shortcuts

---

UPGRADE-1.12.md
UPGRADE-2.0.md

Fixes https://github.com/doctrine/DoctrineBundle/issues/1112

Document UOW reset introduced since 1.12.3/2.0.3

---

UPGRADE-2.1.md

Fixes https://github.com/doctrine/DoctrineBundle/issues/949.
Btw I was trying to find how other people deprecated this and found that nobody actually did, not even Symfony. Not even with readme entry, like we are doing here.

Deprecate .class parameters

---

DependencyInjection/Compiler/EntityListenerPass.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/orm_attach_entity_listener_tag.xml
Tests/DependencyInjection/Fixtures/config/xml/orm_entity_listener_abstract.xml
Tests/DependencyInjection/Fixtures/config/yml/orm_attach_entity_listener_tag.yml
Tests/DependencyInjection/Fixtures/config/yml/orm_entity_listener_abstract.yml

Add priority support for tagged entity listeners

---

Tests/Twig/DoctrineExtensionTest.php
Twig/DoctrineExtension.php

Fix https://github.com/doctrine/DoctrineBundle/issues/1143

Improve replaceQueryParameters function for empty array

---

DependencyInjection/DoctrineExtension.php

When the class name is enclosed in double quotes, it gets turned into bold when being displayed in the webprofiler.

Update deprecation messages to follow the Symfony convention

---

Resources/views/Collector/db.html.twig

When trying to explain a query in the profiler, I had an exception `An exception has been thrown during the rendering of a template ("The controller for URI "/_fragment" is not callable. Controller "DoctrineBundle:Profiler:explain" does neither exist as service nor as class").`
Using the controller method FQCN did solve the problem

Fix render controller when explaining a query

---

DependencyInjection/DoctrineExtension.php
Resources/config/messenger.xml

I have a PR open to Symfony to move the Doctrine transport to a new package. See https://github.com/symfony/symfony/pull/35422
If my Symfony PR is merged, this PR makes sure that DoctrineBundle is compatible with Symfony Messenger 5.1 without any deprecation notices. 
This PR could also be cherry-picked to 1.x branch.

Updated service definition to support Messenger 5.1

---

DependencyInjection/Configuration.php

Starting in Symfony/Config 5.1, calling `NodeDefinition::setDeprecated()` with no arguments is deprecated. See https://github.com/symfony/symfony/pull/35871 
This addresses the deprecation by providing the soon to be required parameters.

fix symfony/config deprecation

---

.doctrine-project.json

DoctrineBundle is missing the project file for the Doctrine website and this PR adds the needed info file `.doctrine-project.json`. It looks like I already had a commit in 2019 but totally forgot about this. :sweat_smile: 
Please check if the branch names and branch infos are correct.

Add doctrine project file for website

---

DependencyInjection/Compiler/CacheSchemaSubscriberPass.php
DependencyInjection/DoctrineExtension.php
DoctrineBundle.php
Resources/config/messenger.xml
Resources/config/orm.xml
Tests/CacheSchemaSubscriberTest.php

For https://github.com/symfony/symfony/pull/36655
This adds service integration for 2 new schema subscribers. They allow `doctrine:schema:update` to automatically see tables needed by Messenger & cache.
I've tested this in a real project and it works beautifully: the table show up only when activated (i.e. when using a `doctrine` transport in messenger or configuring a real cache pool that uses the `pdo` adapter.

Add support for new MessengerTransportDoctrineSchemaSubscriber

---

Resources/doc/entity-listeners.rst

Switching to Symfony 4's new container style: classes for service names.

Update Entity Listener Docs to New Service Style

---

Resources/doc/configuration.rst

See https://github.com/doctrine/dbal/issues/3986
The `schema_filter` key does not filter only tables.

Update comment on the schema_filter key

---

Tests/ProfilerTest.php
Tests/Twig/DoctrineExtensionTest.php
Twig/DoctrineExtension.php
composer.json

Replace unmaintained dependency

---

DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/Fixtures/config/yml/orm_service_single_entity_manager.yml

The `Autoloader` class is always used on bundle boot when the ORM is used.

Preload Autoloader class when the ORM is used

---

.travis.yml
composer.json

This PR:
* allows installing the bundle on PHP 8
* runs tests against PHP 8, allowing failures for the time being.

Test against PHP 8

---

.travis.yml
Tests/Command/ImportMappingDoctrineCommandTest.php
Tests/ContainerTest.php
Tests/DataCollector/DoctrineDataCollectorTest.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/DoctrineExtensionTest.php
Tests/Mapping/ContainerEntityListenerResolverTest.php
Tests/Mapping/DisconnectedMetadataFactoryTest.php
Tests/RegistryTest.php
Tests/Repository/ContainerRepositoryFactoryTest.php
Tests/Repository/ServiceEntityRepositoryTest.php
Tests/ServiceRepositoryTest.php
composer.json

On order to run at least a few tests on php 8, this PR…
* Allows DBAL 3.0 to be installed because DBAL 2 will trigger fatal errors on php 8.
* Uninstalls ORM on the php 8 build because there currently is no ORM version that allows DBAL 3.
* Skips all tests that require ORM if it's not there.
* Ignores deprecation warnings because PHPUnit will trigger lots of them. We need to upgrade PHPUnit to fix this.

Allow DBAL 3.0 and ignore ORM tests on php 8

---

DoctrineBundle.php
Tests/CacheSchemaSubscriberTest.php

The `CacheCollectorPass` of the Cache component decorates the cache adapters with
a `TracingAdapter` which breaks the expectation that the provided Adapter provided to
the `CacheSchemaSubscriber` is a `PdoAdapter` with the `configureSchema` method.
By running the `CacheSchemaSubscriberPass` after the `CacheCollectorPass` only
the actual Adapters (not decorated one) are correctly provided.
Note: This bug only happens when debugging *and* the profiler is enabled.
/cc @weaverryan

[Bug] Run CacheSchemaSubscriberPass after CacheCollectorPass

---

Command/DropDatabaseDoctrineCommand.php

The driver param is stored in global params, so the drop database for shards was throwing an exception.

Bugfix: drop database command was not working with shard argument.

---

Command/Proxy/ImportDoctrineCommand.php

As base command `Doctrine\DBAL\Tools\Console\Command\ImportCommand` had been deprecated in 2.x and removed 3.x, this command should be deprecated as well.

Deprecate ImportDoctrineCommand

---

DependencyInjection/DoctrineExtension.php

~The call might be useless in many versions of Symfony, not sure it's
useless for all of them though. setPrivate is deprecated since 5.2, in
favor of setPublic which is available since 2.0.~
Services are private by default since symfony/dependency-injection 4.0,
which means the deprecated call can safely be dropped.

Address deprecation of Definition::setPrivate()

---

DependencyInjection/Compiler/DoctrineOrmMappingsPass.php
DependencyInjection/DoctrineExtension.php
Resources/config/dbal.xml
Tests/DataCollector/DoctrineDataCollectorTest.php
composer.json

* Allows doctrine/persistence 2.x
* Updates namespace of Doctrine persistence classes in tests.

Allow doctrine/persistence 2.x

---

Resources/config/dbal.xml

Fixes https://github.com/doctrine/DoctrineBundle/issues/1201

fix BC break for removed service alias

---

DoctrineBundle.php

As a result from https://github.com/symfony/symfony/pull/37678, this PR is the last missing piece to implement symfony/uid as DoctrineTypes.

Add symfony uuid to a list of custom types as default uuid/ulid type

---

Tests/ConnectionFactoryTest.php

[In DBAL 2][dbal-2], the signature is: `public function getSchemaManager(Connection $conn);`
[In DBAL 3][dbal-3], there is a new argument: `public function getSchemaManager(Connection $conn, AbstractPlatform $platform);`
This should fix the php 8 job which is the only one which seems to be installing DBAL 3.
[dbal-2]: https://github.com/doctrine/dbal/blob/787c1411233f0fd403565bdb9708d664ced70fe1/lib/Doctrine/DBAL/Driver.php#L42
[dbal-3]: https://github.com/doctrine/dbal/blob/7a5da364badc91edac7022d6e1249c73fd917be3/src/Driver.php#L42

Make method signature compatible with DBAL 2 and 3

---

Tests/ConnectionFactoryTest.php

In doctrine/dbal 3, [the Driver interface contains an extra method](github.com/doctrine/dbal/blob/7a5da364badc91edac7022d6e1249c73fd917be3/src/Driver.php#L47)
Note that this still does not fix the PHP 8 build, and reveals a lot more issues. I think upgrading to PHPUnit 9.3 will help.

Add missing method

---

Resources/views/Collector/db.html.twig

#1210: add different statements metric to the Web Profiler Toolbar

---

Command/CreateDatabaseDoctrineCommand.php
Command/DropDatabaseDoctrineCommand.php

Since dbal 2.11 MasterSlaveConnection is deprecated and the `doctrine:database:create` and` doctrine:database:drop` commands no longer work with the "slaves" option. https://github.com/doctrine/dbal/pull/4054
Issue : #1214

Fix master-slaves deprecation from dbal 2.11

---

Command/Proxy/RunSqlDoctrineCommand.php

See https://github.com/doctrine/DoctrineBundle/issues/1179#issuecomment-704930637

fix issue with doctrine/dbal 2.11 and connection option

---

Command/Proxy/ImportDoctrineCommand.php

The bundle always registers this command. This means that this deprecation is always triggered on every `bin/console` call and the user has no way to fix this deprecation.
This PR proposes to move the deprecation to the `execute()` method - such that it is only triggered when using the command. Moving it in the constructor/`configure()` method does not work, as that is called when using `bin/console` or `bin/console list`.

Only trigger deprecation when command is executed

---

Repository/ContainerRepositoryFactory.php

Symfony <3.3 compat was dropped in https://github.com/doctrine/DoctrineBundle/commit/fe2d0dc803cc18cd02177251b24bd9ffd2882bfe, this code is not needed anymore.

Remove unneeded BC layer

---

composer.json

Hallo,
the DoctrineBundle prevent update twig 2 to twig 3. With this tiny change, it will be works. I have testet it local. All tests are green.
Greatings
Matthias Schobner

Allow twig ^3.0

---

Resources/views/Collector/db.html.twig

Hi. I am getting the following JS error when clicking "Copy" button in Web profiler.
> 250f859?panel=db:2616 Uncaught TypeError: Cannot read property 'writeText' of undefined
at HTMLButtonElement.<anonymous> (50f859?panel=db:2616)
That happens because the Clipboard API is only avaible for secured (HTTPS) connections. Given HTTP is still widely used escpeially on local dev environments I propose hide the "Copy" buttons when it is not supported.

Add navigator.clipboard condition

---

DependencyInjection/Configuration.php
DependencyInjection/DoctrineExtension.php
Resources/config/schema/doctrine-1.0.xsd
Resources/doc/configuration.rst
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
Tests/DependencyInjection/Fixtures/config/xml/dbal_service_single_master_slave_connection.xml
Tests/DependencyInjection/Fixtures/config/yml/dbal_service_single_master_slave_connection.yml
UPGRADE-2.2.md

One problem of this is is that I could not follow DBALs slaves -> replica exactly. Users have `replicas` in YAML instead. This appears to be a limitation of symfony config component, see https://github.com/symfony/symfony/pull/14053#issuecomment-86105385.

#1235 Resolve DBAL 2.11 master/slave deprecations

---

CacheWarmer/DoctrineMetadataCacheWarmer.php
DependencyInjection/Configuration.php
DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/DoctrineExtensionTest.php
UPGRADE-2.2.md

Closes #1186
cc @ostrolucky @dmaicher @nicolas-grekas 
I see two weak places in this implementation:
1. `DoctrineMetadataCacheWarmer` extends `AbstractPhpFileCacheWarmer` which also extended by `ValidatorCacheWarmer`, `SerializerCacheWarmer` and `AnnotationsCacheWarmer` (everywhere `PhpArrayAdapter` used) but it's marked as internal, so BC breaks possible here. I can avoid extending this class but a lot of code will be copy-pasted.
2. Since `PhpArrayAdapter` requires Symfony cache I wrap Doctrine cache with `DoctrineAdapter`. If Doctrine cache is `DoctrineProvider` which wrap a Symfony cache we get a redudant chain of adapters. For example the chain `PhpArrayAdapter -> DoctrineAdapter -> DoctrineProvider -> RedisAdapter` can be simplified by removing `DoctrineAdapter` and …

Add PhpArrayAdapter to cache metadata

---

Command/CreateDatabaseDoctrineCommand.php
Command/DropDatabaseDoctrineCommand.php
DependencyInjection/DoctrineExtension.php
Tests/DependencyInjection/AbstractDoctrineExtensionTest.php

Reverts the changes made in #1240, and applies the passing down of `driverOptions` manually in `CreateDatabaseDoctrineCommand` and `DropDatabaseDoctrineCommand`
Resolves #1252
I haven't written any tests for this - it seems that these commands aren't particularly testable due to the static call to `DriverManager::getConnection`. It's not straightforward to verify the params that are passed to it. I considered refactoring the seemingly common code in both commands into a single parent methods, but there's slight differences between them that makes me wary of breaking something.

Make master connections respect driverOptions

---

Command/CreateDatabaseDoctrineCommand.php
Command/DropDatabaseDoctrineCommand.php

Make sure the primary config gets used over the master so it uses the added options when PrimaryReadReplicaConnection is used. #1257

fix: Prefer primary config over master.

---

DependencyInjection/DoctrineExtension.php
Resources/config/dbal.xml
Tests/ContainerTest.php
Tests/DependencyInjection/Fixtures/DbalTestKernel.php
Tests/TestCase.php
Tests/TestCaseAllPublicCompilerPass.php

I tested this on a real project, it allows to install the project without errors.
Fixes #1262 , fixes #1264 
```shell
composer config repositories.greg0ire vcs https://github.com/greg0ire/DoctrineBundle
composer require doctrine/doctrine-bundle "dev-dbal-3-compat as 2.2.1"
```

Fixes for compatibility with DBAL 3

---

DependencyInjection/DoctrineExtension.php
Resources/doc/configuration.rst
Tests/DependencyInjection/DoctrineExtensionTest.php

This will allow autowiring entity managers by argument type and name which is useful when you have multiple entity managers:
```yaml
orm:
entity_managers:
my_name:
mappings:
MyBundle: []
```
```php
use Doctrine\ORM\EntityManagerInterface;
class Foo
{
public function __construct(EntityManagerInterface $myNameEntityManager) {}
}
```

Autowire entity managers by argument type and name

---

Controller/ProfilerController.php

Fix profiler explain error in SQLServerPlatform, OtherPlatform
